server:
  port: 8081

spring:
  profile:  #-- By this in github the application-prod.yml file will pick up and run it
    active: default
  config:
    import: optional:configserver:http://localhost:8085
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: wiley
    url: jdbc:mysql://localhost:3306/microservices
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

resilience4j:
  retry:
    instances:
      ratingHotelService:
        wait-duration: 5s
        max-attempts: '3'
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        permittedNumberOfCallsInHalfOpenState: '3'
        registerHealthIndicator: 'true'
        minimumNumberOfCalls: '5'
        slidingWindowSize: '10'
        eventConsumerBufferSize: '10'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
management:
  health:
    circuitbreakers:
      enabled: 'true'
  endpoints:
    web:
      exposure:
        include[]: health
  endpoint:
    health:
      showDetails: always

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    preferIpAddress: true

